# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Dan/Desktop/Ahmed/FFT/FFT.cache/wt [current_project]
set_property parent.project_path C:/Users/Dan/Desktop/Ahmed/FFT/FFT.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.2 [current_project]
set_property ip_repo_paths C:/Users/Dan/Desktop/Ahmed/SineWave_Rom_1.0 [current_project]
add_files C:/Users/Dan/Desktop/Ahmed/FFT/FFT.srcs/sources_1/bd/System/System.bd
set_property used_in_implementation false [get_files -all c:/Users/Dan/Desktop/Ahmed/FFT/FFT.srcs/sources_1/bd/System/ip/System_xfft_0_0/System_xfft_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dan/Desktop/Ahmed/FFT/FFT.srcs/sources_1/bd/System/ip/System_processing_system7_0_0/System_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dan/Desktop/Ahmed/FFT/FFT.srcs/sources_1/bd/System/ip/System_axi_dma_0_0/System_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dan/Desktop/Ahmed/FFT/FFT.srcs/sources_1/bd/System/ip/System_axi_dma_0_0/System_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dan/Desktop/Ahmed/FFT/FFT.srcs/sources_1/bd/System/ip/System_axi_dma_0_0/System_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dan/Desktop/Ahmed/FFT/FFT.srcs/sources_1/bd/System/ip/System_rst_processing_system7_0_100M_0/System_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dan/Desktop/Ahmed/FFT/FFT.srcs/sources_1/bd/System/ip/System_rst_processing_system7_0_100M_0/System_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dan/Desktop/Ahmed/FFT/FFT.srcs/sources_1/bd/System/ip/System_rst_processing_system7_0_100M_0/System_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dan/Desktop/Ahmed/FFT/FFT.srcs/sources_1/bd/System/ip/System_xbar_0/System_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dan/Desktop/Ahmed/FFT/FFT.srcs/sources_1/bd/System/ip/System_auto_pc_0/System_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dan/Desktop/Ahmed/FFT/FFT.srcs/sources_1/bd/System/ip/System_auto_pc_1/System_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dan/Desktop/Ahmed/FFT/FFT.srcs/sources_1/bd/System/ip/System_auto_us_0/System_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dan/Desktop/Ahmed/FFT/FFT.srcs/sources_1/bd/System/ip/System_auto_us_0/System_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dan/Desktop/Ahmed/FFT/FFT.srcs/sources_1/bd/System/ip/System_auto_us_1/System_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dan/Desktop/Ahmed/FFT/FFT.srcs/sources_1/bd/System/ip/System_auto_us_1/System_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Dan/Desktop/Ahmed/FFT/FFT.srcs/sources_1/bd/System/System_ooc.xdc]
set_property is_locked true [get_files C:/Users/Dan/Desktop/Ahmed/FFT/FFT.srcs/sources_1/bd/System/System.bd]

read_vhdl -library xil_defaultlib C:/Users/Dan/Desktop/Ahmed/FFT/FFT.srcs/sources_1/bd/System/hdl/System_wrapper.vhd
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file System_wrapper.hwdef }
synth_design -top System_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef System_wrapper.dcp
catch { report_utilization -file System_wrapper_utilization_synth.rpt -pb System_wrapper_utilization_synth.pb }
